export enum FINANCE_CURRENSIES {
  GOLD = 'GOLD',
  SILVER = 'SILVER',
  PLATINUM = 'PLATINUM',
}

export const FINANCE_NAMES = {
  [FINANCE_CURRENSIES.GOLD]: 'Золото',
  [FINANCE_CURRENSIES.SILVER]: 'Серебро',
  [FINANCE_CURRENSIES.PLATINUM]: 'Бронза'
}
