import { MOVE_DIRECTIONS } from '~/stores/map/index.constants'

export const MOVE_DIRECTIONS_SYMBOLS = {
  [MOVE_DIRECTIONS.TOP]: '↑',
  [MOVE_DIRECTIONS.BOTTOM]: '↓',
  [MOVE_DIRECTIONS.LEFT]: '←',
  [MOVE_DIRECTIONS.RIGHT]: '→'
}

export const ALL_POSSIBLE_DIRECTIONS = [
  MOVE_DIRECTIONS.TOP,
  MOVE_DIRECTIONS.BOTTOM,
  MOVE_DIRECTIONS.LEFT,
  MOVE_DIRECTIONS.RIGHT
]
